export const parcels = [
  {
    id: "p1",
    top: "6%",
    right: "8%",
    width: "18%",
    height: "15%",
    tone: "bg-yellow-300/70",
    rotate: -4,
    title: "قطعه مسکونی A",
  },
  {
    id: "p2",
    top: "8%",
    right: "30%",
    width: "22%",
    height: "16%",
    tone: "bg-yellow-300/65",
    rotate: 5,
    title: "قطعه مسکونی B",
  },
  {
    id: "p3",
    top: "6%",
    right: "56%",
    width: "19%",
    height: "14%",
    tone: "bg-emerald-300/55",
    rotate: -3,
    title: "فضای سبز",
  },
  {
    id: "p4",
    top: "25%",
    right: "12%",
    width: "20%",
    height: "16%",
    tone: "bg-yellow-300/65",
    rotate: 2,
    title: "مجتمع تجاری",
  },
  {
    id: "p5",
    top: "26%",
    right: "38%",
    width: "18%",
    height: "13%",
    tone: "bg-yellow-300/70",
    rotate: -5,
    title: "قطعه C",
  },
  {
    id: "p6",
    top: "24%",
    right: "62%",
    width: "22%",
    height: "16%",
    tone: "bg-yellow-300/60",
    rotate: 4,
    title: "قطعه D",
  },
  {
    id: "p7",
    top: "46%",
    right: "10%",
    width: "24%",
    height: "18%",
    tone: "bg-yellow-300/70",
    rotate: -2,
    title: "قطعه E",
  },
  {
    id: "p8",
    top: "48%",
    right: "40%",
    width: "19%",
    height: "14%",
    tone: "bg-emerald-300/45",
    rotate: 3,
    title: "پارکینگ عمومی",
  },
  {
    id: "p9",
    top: "46%",
    right: "63%",
    width: "23%",
    height: "17%",
    tone: "bg-yellow-300/65",
    rotate: -6,
    title: "قطعه F",
  },
];
